export const resources = [
  {
    key: 'health',
    title: 'Health',
    path: '/api/health',
    supportsCrud: false,
    sampleGetById: '1',
    sampleCreate: {},
    sampleUpdate: {},
  },
  {
    key: 'categories',
    title: 'Categories',
    path: '/api/categories',
    supportsCrud: true,
    sampleGetById: '1',
    sampleDeleteId: '1',
    sampleUpdateId: '1',
    sampleCreate: {
      name: 'Burgers',
      description: 'Burger and sandwich items',
    },
    sampleUpdate: {
      name: 'Burgers Updated',
      description: 'Updated description',
    },
  },
  {
    key: 'users',
    title: 'Users',
    path: '/api/users',
    supportsCrud: true,
    sampleGetById: '1',
    sampleDeleteId: '1',
    sampleUpdateId: '1',
    sampleCreate: {
      fullName: 'Akash Sharma',
      email: 'akash@example.com',
      phone: '9876543210',
    },
    sampleUpdate: {
      fullName: 'Akash Sharma Updated',
      email: 'akash.updated@example.com',
      phone: '9123456780',
    },
  },
  {
    key: 'menu-items',
    title: 'Menu Items',
    path: '/api/menu-items',
    supportsCrud: true,
    sampleGetById: '1',
    sampleDeleteId: '1',
    sampleUpdateId: '1',
    sampleCreate: {
      name: 'Cheese Burger',
      description: 'Double patty burger',
      price: 199.0,
      available: true,
      categoryId: 1,
    },
    sampleUpdate: {
      name: 'Cheese Burger XL',
      description: 'Bigger version',
      price: 229.0,
      available: true,
      categoryId: 1,
    },
  },
  {
    key: 'orders',
    title: 'Orders',
    path: '/api/orders',
    supportsCrud: true,
    sampleGetById: '1',
    sampleDeleteId: '1',
    sampleUpdateId: '1',
    sampleCreate: {
      userId: 1,
      status: 'CREATED',
      totalAmount: 398.0,
      placedAt: '2026-03-30T12:00:00',
    },
    sampleUpdate: {
      userId: 1,
      status: 'CONFIRMED',
      totalAmount: 398.0,
      placedAt: '2026-03-30T12:30:00',
    },
  },
  {
    key: 'order-items',
    title: 'Order Items',
    path: '/api/order-items',
    supportsCrud: true,
    sampleGetById: '1',
    sampleDeleteId: '1',
    sampleUpdateId: '1',
    sampleCreate: {
      orderId: 1,
      menuItemId: 1,
      quantity: 2,
      unitPrice: 199.0,
      lineTotal: 398.0,
    },
    sampleUpdate: {
      orderId: 1,
      menuItemId: 1,
      quantity: 3,
      unitPrice: 199.0,
      lineTotal: 597.0,
    },
  },
]
